# Generated by Django 2.2.4 on 2019-10-04 00:21

import api.grain.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grain', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='samplegrain',
            name='total_grains',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='samplegrain',
            name='image',
            field=models.ImageField(upload_to=api.grain.models.sample_path),
        ),
    ]
