# Generated by Django 2.2.4 on 2019-10-04 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grain', '0004_auto_20191004_1341'),
    ]

    operations = [
        migrations.AddField(
            model_name='sampledetailgrain',
            name='area',
            field=models.FloatField(default=0),
        ),
    ]
