# Generated by Django 2.2.4 on 2019-10-04 19:57

import api.grain.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grain', '0005_sampledetailgrain_area'),
    ]

    operations = [
        migrations.AddField(
            model_name='samplegrain',
            name='image_recognized_grains',
            field=models.ImageField(blank=True, upload_to=api.grain.models.sample_path),
        ),
    ]
