# Generated by Django 2.2.4 on 2019-10-28 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grain', '0007_sampledetailgrain_type_grain_detail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='analysisgrain',
            name='type_grain',
        ),
        migrations.AddField(
            model_name='sampledetailgrain',
            name='diameter_grain',
            field=models.FloatField(default=0),
        ),
    ]
