# Generated by Django 2.2.4 on 2019-10-31 13:42

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('grain', '0008_auto_20191028_2242'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='analysisgrain',
            options={'ordering': ['sample__name_sample'], 'verbose_name_plural': 'Analysis Grains'},
        ),
        migrations.CreateModel(
            name='PercentageTypeGrain',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('percentage', models.FloatField(default=0)),
                ('analysis_percent_grain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='percent_analysis', to='grain.AnalysisGrain')),
                ('percent_type_grain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='percent_type', to='grain.TypeGrain')),
            ],
            options={
                'verbose_name': 'Percentage Type Grain',
                'verbose_name_plural': 'Percentage Types Grain',
            },
        ),
    ]
