# Generated by Django 2.2.4 on 2019-10-31 17:41

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('grain', '0009_auto_20191031_1342'),
    ]

    operations = [
        migrations.CreateModel(
            name='CatergoryGrain',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('min_measure', models.FloatField(default=0)),
                ('max_measure', models.FloatField(default=0)),
            ],
            options={
                'verbose_name': 'Catergory Grain',
                'verbose_name_plural': 'Catergories Grains',
                'ordering': ['name'],
            },
        ),
    ]
