# Generated by Django 2.2.4 on 2019-09-25 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quinoas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quinua',
            name='datetimer',
            field=models.DateTimeField(auto_now_add=True, default='2019-09-21'),
            preserve_default=False,
        ),
    ]
