# Generated by Django 2.2.4 on 2019-09-25 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quinoas', '0003_auto_20190925_2136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quinua',
            name='datetimer',
            field=models.DateTimeField(),
        ),
    ]
