# Generated by Django 2.2.4 on 2019-09-25 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quinoas', '0004_auto_20190925_2137'),
    ]

    operations = [
        migrations.AddField(
            model_name='quinua',
            name='image',
            field=models.ImageField(default=None, upload_to='media/'),
            preserve_default=False,
        ),
    ]
