# Generated by Django 2.2.4 on 2019-09-25 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quinoas', '0005_quinua_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quinua',
            name='datetimer',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
