# Generated by Django 2.2.4 on 2019-09-26 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quinoas', '0009_auto_20190926_0227'),
    ]

    operations = [
        migrations.AddField(
            model_name='sample',
            name='total',
            field=models.FloatField(default=0.0),
        ),
    ]
